// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_omg__survive_8_rounds = "CggIo5_16TsQAhAG"; // <GPGSID>
        public const string achievement_wtf__lose_3_games_in_a_row = "CggIo5_16TsQAhAD"; // <GPGSID>
        public const string package_name = "com.AnachronicDesigns.SadPaddleDeluxe"; // <GPGSID>
        public const string leaderboard_infinite = "CggIo5_16TsQAhAJ"; // <GPGSID>
        public const string leaderboard_classic = "CggIo5_16TsQAhAI"; // <GPGSID>
        public const string achievement_fufufu__lose_7_games_in_a_row = "CggIo5_16TsQAhAF"; // <GPGSID>
        public const string achievement_f_yeah__survive_3_rounds = "CggIo5_16TsQAhAE"; // <GPGSID>
        public const string achievement_herp_derp__fail_to_score = "CggIo5_16TsQAhAA"; // <GPGSID>
        public const string achievement_ok__commit_to_flat = "CggIo5_16TsQAhAH"; // <GPGSID>
        public const string achievement_challenge_accepted__ironic = "CggIo5_16TsQAhAC"; // <GPGSID>
        public const string achievement_forever_alone__play_5_games = "CggIo5_16TsQAhAB"; // <GPGSID>

}

